FROM node:lts-alpine3.23 as build

WORKDIR /app

COPY package*.json .

RUN npm ci

COPY . .

RUN npm run build

FROM node:lts-alpine3.23

WORKDIR /app

COPY package*.json .

RUN npm ci

COPY --from=build /app/dist ./dist

EXPOSE 4000

CMD [ "npm","start" ]