// src/utils/courseUtils.js

// --- ASSET IMPORTS ---
// Catalog Images
import WhyCyber from '../assets/whylearncyber.jpg';
import WhyDS from '../assets/whylearndatascince.jpeg';
import WhyDA from '../assets/whylearndataana.jpeg';
import WhyAI from '../assets/whyaiml.png';

// Detail Images (Career / Gain)
import CareerCyber from '../assets/carrerincyber.jpeg';
import GainCyber from '../assets/gainincyber.jpeg';

import CareerDS from '../assets/carrerindatascience.jpeg';
import GainDS from '../assets/gainindatascience.jpeg';

import CareerDA from '../assets/carrerindataana.jpeg';
import GainDA from '../assets/gainindatascience.jpeg';

import CareerAI from '../assets/carrerinaiml.png';
import GainAI from '../assets/gainaiml.png';

//  NEW:Import hero images for the special courses
import examPrepHero from '../assets/exmprepkit.jpeg';
import careerTransitionHero from '../assets/carrertran.jpeg';
import aiLearningHero from '../assets/aipowered.jpeg';

// --- VIDEO ASSETS (CLOUDINARY) ---
const CyberVideo =
  'https://res.cloudinary.com/dhtxeigzx/video/upload/v1769757258/C_S_yyglnw.mp4';
const DataScienceVideo =
  'https://res.cloudinary.com/dsgbhkzpg/video/upload/v1770297988/DSs_e8qobp.mp4';
const DataAnalyticsVideo =
  'https://res.cloudinary.com/dhtxeigzx/video/upload/v1769844972/DA_zw9avx.mp4';
const AIMLVideo =
  'https://res.cloudinary.com/dhtxeigzx/video/upload/v1769753171/Blue_Futuristic_Artificial_Intelligence_Video_1_ubonrm.mp4';

/*
 * s a URL-friendly slug from a course title.
 * This function MUST match the logic used in BuiltForEveryone.
 * @param {object} c - The course object.
 * @returns {string} The generated slug.
 */
export const getSlug = (c: any) => {
  if (!c || !c.title) return '';

  // Handle special cases first
  if (c.title.toLowerCase().includes('ai & machine learning')) {
    return 'ai-ml-engineer';
  }

  return c.title
    .toLowerCase()
    .replace(/ \/ /g, '-') // Handles "Data Science / AI"
    .replace(/\//g, '-') // Handles other slashes
    .replace(/ & /g, '-') // Handles "AI & ML"
    .replace(/ /g, '-'); // Replaces spaces with hyphens
};

// --- UPDATED: Add new hero images to the map ---
export const getCatalogImage = (c: any) => {
  const slug = getSlug(c);
  const map = {
    'data-science': WhyDS,
    'data-analytics': WhyDA,
    'cyber-security': WhyCyber,
    'ai-ml-engineer': WhyAI,
    'ai-ml': WhyAI,
    // CORRECTED: Use the exact slugs generated by getSlug
    'exam-preparation-kit': examPrepHero,
    'career-transition-programs': careerTransitionHero,
    'ai-powered-learning-paths': aiLearningHero,
  };
  // Return mapped image or a default
  return (map as Record<string, string>)[slug] || c?.thumbnail || WhyCyber;
};

// --- UPDATED: This function is not used for the new courses, but kept for completeness ---
export const getHeroVideo = (c: any) => {
  const slug = getSlug(c);
  const map = {
    'cyber-security': CyberVideo,
    'data-science': DataScienceVideo,
    'data-analytics': DataAnalyticsVideo,
    'ai-ml-engineer': AIMLVideo,
    'ai-ml': AIMLVideo,
    // These courses don't use videos, but adding them for consistency
    'exam-preparation-kit': CyberVideo, // Fallback
    'career-transition-programs': CyberVideo, // Fallback
    'ai-powered-learning-paths': AIMLVideo, // Fallback
  };
  return (map as Record<string, string>)[slug] || CyberVideo; // Default fallback
};

// --- UPDATED: Add detail images for the new courses ---
export const getDetailImages = (c: any) => {
  const slug = getSlug(c);
  const map = {
    'cyber-security': { career: CareerCyber, gain: GainCyber },
    'data-science': { career: CareerDS, gain: GainDS },
    'data-analytics': { career: CareerDA, gain: GainDA },
    'ai-ml-engineer': { career: CareerAI, gain: GainAI },
    'ai-ml': { career: CareerAI, gain: GainAI },
    // CORRECTED: Use the exact slugs and provide relevant images
    'exam-preparation-kit': { career: CareerCyber, gain: GainCyber },
    'career-transition-programs': { career: CareerCyber, gain: GainCyber }, // Using cyber as a placeholder
    'ai-powered-learning-paths': { career: CareerAI, gain: GainAI },
  };
  return (
    (map as Record<string, { career: string; gain: string }>)[slug] || {
      career: CareerCyber,
      gain: GainCyber,
    }
  ); // Default fallback
};
